INSERT INTO USERS (ID, USERNAME,PASSWORD) VALUES (1, 'admin@pixeltrice.com','$2a$08$fL7u5xcvsZl78su29x1ti.dxI.9rYO8t0q5wk2ROJ.1cdR53bmaVG');

INSERT INTO TICKET (ID, START_DESTINATION,END_DESTINATION, PRICE, UPDATE_DATE, DEPARTURE_DATE, DEPARTURE_TIME) VALUES (1, 'Kathmandu', 'Pokhara', 2500, NOW(), NOW(), '10:00:00');
INSERT INTO TICKET (ID, START_DESTINATION,END_DESTINATION, PRICE, UPDATE_DATE, DEPARTURE_DATE, DEPARTURE_TIME) VALUES (2, 'Kathmandu', 'Biratnagar', 3000, NOW(), current_date-1, '10:00:00');
INSERT INTO TICKET (ID, START_DESTINATION,END_DESTINATION, PRICE, UPDATE_DATE, DEPARTURE_DATE, DEPARTURE_TIME) VALUES (3, 'Kathmandu', 'Butwal', 2000, NOW(), current_date-2, '10:00:00');
INSERT INTO TICKET (ID, START_DESTINATION,END_DESTINATION, PRICE, UPDATE_DATE, DEPARTURE_DATE, DEPARTURE_TIME) VALUES (4, 'Kathmandu', 'Nepalgunj', 4000, NOW(), current_date-1, '10:00:00');


INSERT INTO RESERVATION (TICKET_ID,TOTAL_TICKET, NAME, TOTAL_PRICE, UPDATE_DATE, USER_ID) VALUES (1, 2, 'Ashish', 5000, NOW(), 1);
INSERT INTO RESERVATION (TICKET_ID,TOTAL_TICKET, NAME, TOTAL_PRICE, UPDATE_DATE, USER_ID) VALUES (1, 3, 'Ram', 7500, NOW(), 1);
INSERT INTO RESERVATION (TICKET_ID,TOTAL_TICKET, NAME, TOTAL_PRICE, UPDATE_DATE, USER_ID) VALUES (2, 3, 'Shyam', 9000, current_date-1, 1);
INSERT INTO RESERVATION (TICKET_ID,TOTAL_TICKET, NAME, TOTAL_PRICE, UPDATE_DATE, USER_ID) VALUES (3, 2, 'Hari', 4000, current_date-2, 1);
INSERT INTO RESERVATION (TICKET_ID,TOTAL_TICKET, NAME, TOTAL_PRICE, UPDATE_DATE, USER_ID) VALUES (4, 2, 'Sita', 4000, current_date-1, 1);