CREATE TABLE USERS (ID INT PRIMARY KEY, USERNAME VARCHAR(50), PASSWORD VARCHAR(70));
CREATE TABLE TICKET(ID INT PRIMARY KEY, START_DESTINATION VARCHAR(50), END_DESTINATION VARCHAR(70),PRICE INT, UPDATE_DATE DATETIME,DEPARTURE_DATE DATE, DEPARTURE_TIME TIME);
CREATE TABLE RESERVATION (ID INT NOT NULL AUTO_INCREMENT,TICKET_ID INT, USER_ID INT,TOTAL_TICKET INT, NAME VARCHAR(20),TOTAL_PRICE INT, UPDATE_DATE DATETIME, PRIMARY KEY (ID),FOREIGN KEY (TICKET_ID) REFERENCES TICKET(ID),FOREIGN KEY (USER_ID) REFERENCES USERS(ID));
CREATE TABLE PAYMENT (ID INT NOT NULL AUTO_INCREMENT, RESERVATION_ID INT, UPDATE_DATE DATETIME,PRIMARY KEY (ID),FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION(ID))
